spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://localhost:5432/identityauth
    username: identity_user
    password: identity_user

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.youtube.identityauthservice: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
