replicaCount: 3

image:
  repository: acr.azure.io/youtube-platform/edge-cdn-control-service
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: true
  name: edge-cdn-control-service

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: edge-cdn-control.youtube.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 2

networkPolicy:
  enabled: true

config:
  azure:
    subscriptionId: ""
    tenantId: ""
  postgres:
    url: ""
    user: ""
    password: ""
  redis:
    host: "redis-service.redis.svc.cluster.local"
    port: 6379

