apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moderation-service
  template:
    metadata:
      labels:
        app: moderation-service
    spec:
      containers:
        - name: app
          image: moderation-service:local
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
          envFrom:
            - secretRef:
                name: moderation-service-secrets


