spring:
  cloud:
    azure:
      appconfiguration:
        enabled: true
      keyvault:
        secret:
          enabled: true
      cosmos:
        consistency-level: Session

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.youtube.experimentationservice: INFO

