spring:
  cloud:
    azure:
      appconfiguration:
        enabled: false
      keyvault:
        secret:
          enabled: false
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT:https://localhost:8081}
        key: ${AZURE_COSMOS_KEY:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==}
        database: experimentation
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.youtube.experimentationservice: DEBUG

