apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anti-abuse-service.fullname" . }}-secrets
type: Opaque
stringData:
  cosmos-endpoint: {{ .Values.secrets.cosmos.endpoint }}
  cosmos-key: {{ .Values.secrets.cosmos.key }}
  ml-endpoint-url: {{ .Values.secrets.ml.endpointUrl }}
  ml-api-key: {{ .Values.secrets.ml.apiKey }}
  oauth2-issuer-uri: {{ .Values.secrets.oauth2.issuerUri }}

