apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: observability-service-pdb
  namespace: youtube-mvp
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: observability-service

