spring:
  data:
    redis:
      host: localhost
      port: 6379
  
  cloud:
    azure:
      cosmos:
        endpoint: https://localhost:8081/
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: youtube-mvp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/test
          jwk-set-uri: http://localhost:8080/auth/realms/test/protocol/openid-connect/certs

server:
  port: 8080

logging:
  level:
    com.youtube.mvp: DEBUG
    com.azure: DEBUG

cdn:
  base-url: http://localhost:9000

jwt:
  secret: local-secret-key-for-testing-only-minimum-32-characters
  issuer: streaming-service-local

policy:
  allow-anonymous: true

