spring:
  application:
    name: drm-service
  
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
      profile:
        tenant-id: ${AZURE_TENANT_ID}
        cloud-type: Azure
      
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        key: ${AZURE_COSMOS_KEY}
        database: ${AZURE_COSMOS_DATABASE:youtube-mvp}
        consistency-level: Session
        
      servicebus:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
        topic-name: ${AZURE_SERVICE_BUS_TOPIC:drm-events}
        
      appconfiguration:
        enabled: true
        endpoint: ${AZURE_APP_CONFIG_ENDPOINT}
        
      keyvault:
        secrets:
          enabled: true
          endpoint: ${AZURE_KEY_VAULT_ENDPOINT}
      
      media-services:
        endpoint: ${AZURE_MEDIA_SERVICES_ENDPOINT}
        subscription-id: ${AZURE_SUBSCRIPTION_ID}
        resource-group: ${AZURE_RESOURCE_GROUP}
    
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}
        ssl:
          enabled: ${REDIS_SSL_ENABLED:false}
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1ms
      
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        open-in-view: false
    
    datasource:
      url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/youtube_mvp}
      username: ${DATASOURCE_USERNAME:postgres}
      password: ${DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  
logging:
  level:
    root: INFO
    com.youtube.drmservice: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      azure:
        enabled: true
    distribution:
      percentiles-histogram:
        enabled: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
        drm.policy.operations: 0.5,0.9,0.95,0.99

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ams-operation:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      ams-operation:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  rateLimiter:
    instances:
      policy-endpoint:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
  timelimiter:
    instances:
      ams-operation:
        timeoutDuration: 3s

# Custom configuration
drm:
  cache:
    ttl: 3600
  key-rotation:
    schedule: "0 */30 * * * *"  # Every 30 minutes

info:
  version: 1.0
  name: DRM Service

