spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://localhost:8081
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: comments
        auto-create: true
        cosmos-endpoint-disabled: false
    
    data:
      redis:
        host: localhost
        port: 6379

azure:
  cosmos:
    database: comments
    container: comments

logging:
  level:
    root: INFO
    com.youtube.commentsservice: DEBUG
    com.azure: DEBUG

# Disable OAuth2 for local development
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json
          # For local testing without OAuth2, use a mock configuration

