version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: feeds-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass mypass
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - feeds-network

  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmos-emulator
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://localhost:8081/_explorer/emulator.pem || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - feeds-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    networks:
      - feeds-network

  feeds-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feeds-service
    depends_on:
      redis:
        condition: service_healthy
      cosmos-emulator:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypass
      - COSMOS_URI=https://localhost:8081
      - COSMOS_KEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - COSMOS_DATABASE=feeds-db
      - SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=TestKey
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    networks:
      - feeds-network

volumes:
  azurite-data:

networks:
  feeds-network:
    driver: bridge

