# NOTE: This is a template. In production, use Azure Key Vault or sealed secrets.
# Never commit actual secrets to version control.

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: youtube-mvp
type: Opaque
stringData:
  host: "your-redis-host.redis.cache.windows.net"
  port: "6380"
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmos-secrets
  namespace: youtube-mvp
type: Opaque
stringData:
  endpoint: "https://your-cosmos-account.documents.azure.com:443/"
  key: "YOUR_COSMOS_KEY_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: youtube-mvp
type: Opaque
stringData:
  secret: "YOUR_JWT_SECRET_HERE_MIN_32_CHARS"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-configuration-secrets
  namespace: youtube-mvp
type: Opaque
stringData:
  connection-string: "Endpoint=https://your-config.azconfig.io;Id=YOUR_ID;Secret=YOUR_SECRET"

