replicaCount: 3

image:
  repository: anti-abuse-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  redis:
    host: redis.default.svc.cluster.local
  cosmos:
    database: anti-abuse
  ml:
    endpointUrl: ""
    apiKey: ""

secrets:
  cosmos:
    endpoint: ""
    key: ""
  ml:
    endpointUrl: ""
    apiKey: ""
  oauth2:
    issuerUri: ""

