version: '3.8'

services:
  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmos-emulator
    ports:
      - "8081:8081"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITIONCOUNT=10
    networks:
      - youtube-mvp-network

  servicebus:
    image: mcr.microsoft.com/azure-messaging-servicebus:latest
    container_name: servicebus-emulator
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - AMQP_PORT=5672
    networks:
      - youtube-mvp-network

networks:
  youtube-mvp-network:
    driver: bridge
