apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-cdn-control-service
  namespace: youtube-platform
  labels:
    app: edge-cdn-control-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge-cdn-control-service
  template:
    metadata:
      labels:
        app: edge-cdn-control-service
        version: v1
    spec:
      serviceAccountName: edge-cdn-control-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
      - name: edge-cdn-control-service
        image: acr.azure.io/youtube-platform/edge-cdn-control-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: azure-subscription-id
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: azure-tenant-id
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: azure-client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: azure-client-secret
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: postgres-url
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: edge-cdn-control-secrets
              key: postgres-password
        - name: REDIS_HOST
          value: "redis-service.redis.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: OAUTH2_ISSUER_URI
          value: "https://login.microsoftonline.com/$(AZURE_TENANT_ID)/v2.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: acr-secret

