spring:
  application:
    name: recommendations-service
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  # Datasource Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/recommendations}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  # Flyway Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
  
  # Azure Cosmos DB
  azure:
    cosmos:
      uri: ${AZURE_COSMOS_URI:}
      key: ${AZURE_COSMOS_KEY:}
      database: ${AZURE_COSMOS_DATABASE:recommendations}
      enabled: true
  
  # Azure Service Bus
  cloud:
    azure:
      servicebus:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING:}
  
  # Security OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://login.microsoftonline.com/{tenantId}/v2.0}
          jwk-set-uri: ${JWT_ISSUER_URI:https://login.microsoftonline.com/{tenantId}/discovery/v2.0/keys}

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 25
        maxWaitDuration: 5000ms
  ratelimiter:
    configs:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 60s
        timeoutDuration: 0

# Logging Configuration
logging:
  level:
    root: INFO
    com.youtube.recommendationsservice: DEBUG
    org.springframework.security: INFO
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Configuration
app:
  recommendations:
    default-limit: 20
    max-limit: 100
    cache-ttl: 3600
    fallback-enabled: true

