replicaCount: 3

image:
  repository: experimentation-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  redis:
    host: redis.default.svc.cluster.local
  cosmos:
    database: experimentation

secrets:
  cosmos:
    endpoint: ""
    key: ""
  oauth2:
    issuerUri: ""

