spring:
  application:
    name: monetization-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/monetization}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
    open-in-view: false
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  cloud:
    azure:
      servicebus:
        namespace: ${AZURE_SB_NAMESPACE:}
        connection-string: ${AZURE_SB_CONNECTION_STRING:}
      keyvault:
        secret:
          enabled: true
          property-sources:
            - name: keyvault
              endpoint: ${AZURE_KEYVAULT_URI:}
      appconfiguration:
        enabled: ${AZURE_APP_CONFIG_ENABLED:false}
        endpoint: ${AZURE_APP_CONFIGURATION_ENDPOINT:}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      probes:
        enabled: true
  health:
    redis:
      enabled: true

logging:
  level:
    root: INFO
    com.youtube.monetizationservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
    instances:
      payment-webhook:
        maxAttempts: 3
        waitDuration: 2s
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      payment-provider:
        slidingWindowSize: 20
        failureRateThreshold: 70
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 10s
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s

monetization:
  payment:
    webhook-secret-key: ${PAYMENT_WEBHOOK_SECRET_KEY:}
    idempotency-ttl: ${IDEMPOTENCY_TTL:86400}
  membership:
    default-billing-cycle-days: 30

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

