apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-telemetry-service.fullname" . }}
  labels:
    {{- include "analytics-telemetry-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "analytics-telemetry-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "analytics-telemetry-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "analytics-telemetry-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "azure"
        - name: SERVER_PORT
          value: "8080"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-config
              key: redis.host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-config
              key: redis.port
        - name: EVENT_HUB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-config
              key: eventhubs.event-hub-name
        - name: DLQ_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-config
              key: storage.dlq-container-name
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-secrets
              key: redis.password
        - name: EVENT_HUBS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-secrets
              key: eventhubs.connection-string
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-secrets
              key: storage.connection-string
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "analytics-telemetry-service.fullname" . }}-secrets
              key: app-insights.connection-string
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

