replicaCount: 3

image:
  repository: config-secrets-service
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: config-secrets.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 2

networkPolicy:
  enabled: true

secrets:
  databaseUrl: ""
  databaseUsername: ""
  databasePassword: ""
  appConfigEndpoint: ""
  keyVaultUri: ""
  serviceBusConnectionString: ""
  jwtIssuerUri: "https://login.microsoftonline.com/{tenantId}/v2.0"
  jwtJwkSetUri: "https://login.microsoftonline.com/{tenantId}/discovery/v2.0/keys"

serviceAccount:
  create: true
  name: ""
  annotations: {}

config:
  springProfilesActive: "prod"
  redisHost: "redis-service"
  redisPort: "6379"

