spring:
  application:
    name: channel-service
  
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
      profile:
        tenant-id: ${AZURE_TENANT_ID}
        cloud-type: Azure
      
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        key: ${AZURE_COSMOS_KEY}
        database: ${AZURE_COSMOS_DATABASE:youtube-mvp}
        consistency-level: Session
        
      servicebus:
        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
        entity-name: ${AZURE_SERVICE_BUS_TOPIC:subscriptions}
        
      appconfiguration:
        enabled: true
        endpoint: ${AZURE_APP_CONFIG_ENDPOINT}
        
      keyvault:
        secrets:
          enabled: true
          endpoint: ${AZURE_KEY_VAULT_ENDPOINT}
    
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}
        ssl:
          enabled: ${REDIS_SSL_ENABLED:false}
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1ms
      
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        open-in-view: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  
logging:
  level:
    root: INFO
    com.youtube.channelservice: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.cosmos: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      azure:
        enabled: true
    distribution:
      percentiles-histogram:
        enabled: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
        subscriptions.count: 0.5,0.9,0.95,0.99

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true

resilience4j:
  circuitbreaker:
    instances:
      subscription-operation:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      subscription-operation:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  rateLimiter:
    instances:
      subscription-endpoint:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
  timelimiter:
    instances:
      subscription-operation:
        timeoutDuration: 3s

# Custom configuration
channel:
  service:
    subscription:
      idempotency:
        ttl: PT24H
      cache:
        enabled: true
        ttl: PT1H
      anti-supernode:
        enabled: true
        shard-suffix-length: 2
