spring:
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379

azure:
  cosmos:
    endpoint: http://localhost:8081
    key: local-key
    database: notifications

app:
  servicebus:
    topics:
      notifications: notifications-jobs


