replicaCount: 3

image:
  repository: content-id-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: content-id-service.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

database:
  url: ""
  username: ""
  password: ""

redis:
  host: redis-service
  port: 6379

azure:
  cosmos:
    endpoint: ""
    key: ""
    database: contentid
  storage:
    connectionString: ""
  serviceBus:
    connectionString: ""
  eventHubs:
    connectionString: ""
    eventHubName: match-events
  appConfiguration:
    enabled: true
    connectionString: ""
  keyVault:
    enabled: true
    endpoint: ""

spring:
  profiles:
    active: prod

security:
  oauth2:
    issuerUri: ""
    jwkSetUri: ""

