spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://localhost:8081/
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: youtube-mvp
        consistency-level: SESSION
      servicebus:
        connection-string: Endpoint=sb://localhost:5672/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=test

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/test
          jwk-set-uri: http://localhost:8080/auth/realms/test/protocol/openid-connect/certs

server:
  port: 8080

logging:
  level:
    com.youtube.mvp: DEBUG
    com.azure: DEBUG

