spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://localhost:8081
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: youtube-mvp-test
      
      servicebus:
        connection-string: Endpoint=sb://localhost:5672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=test
        entity-name: captions
  
    data:
      redis:
        host: localhost
        port: 6379
        password: 
        ssl:
          enabled: false

azure:
  storage:
    connection-string: UseDevelopmentStorage=true
    captions-container: captions-dev
  
  speech:
    key: local-dev-key
    region: centralus
  
  translator:
    endpoint: http://localhost:5000
    key: local-dev-key

logging:
  level:
    com.youtube.captionssubtitlesservice: DEBUG
