apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-secrets-service.fullname" . }}
  labels:
    {{- include "config-secrets-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "config-secrets-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "config-secrets-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "config-secrets-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.config.springProfilesActive | quote }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "config-secrets-service.fullname" . }}-secrets
              key: database-url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "config-secrets-service.fullname" . }}-secrets
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "config-secrets-service.fullname" . }}-secrets
              key: database-password
        - name: REDIS_HOST
          value: {{ .Values.config.redisHost | quote }}
        - name: REDIS_PORT
          value: {{ .Values.config.redisPort | quote }}
        - name: AZURE_APP_CONFIG_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ include "config-secrets-service.fullname" . }}-secrets
              key: app-config-endpoint
        - name: AZURE_KEY_VAULT_URI
          valueFrom:
            secretKeyRef:
              name: {{ include "config-secrets-service.fullname" . }}-secrets
              key: key-vault-uri
        - name: AZURE_SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "config-secrets-service.fullname" . }}-secrets
              key: service-bus-connection-string
        - name: JWT_ISSUER_URI
          value: {{ .Values.secrets.jwtIssuerUri | quote }}
        - name: JWT_JWK_SET_URI
          value: {{ .Values.secrets.jwtJwkSetUri | quote }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

