apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-secrets-service.fullname" . }}-secrets
  labels:
    {{- include "config-secrets-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc }}
  database-username: {{ .Values.secrets.databaseUsername | b64enc }}
  database-password: {{ .Values.secrets.databasePassword | b64enc }}
  app-config-endpoint: {{ .Values.secrets.appConfigEndpoint | b64enc }}
  key-vault-uri: {{ .Values.secrets.keyVaultUri | b64enc }}
  service-bus-connection-string: {{ .Values.secrets.serviceBusConnectionString | b64enc }}

