replicaCount: 3

image:
  repository: <registry>/observability-service
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: observability-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 2

networkPolicy:
  enabled: true

config:
  springProfilesActive: "azure"
  redisHost: "redis-service"
  redisPort: "6379"

secrets:
  datasourceUrl: ""
  datasourceUsername: ""
  datasourcePassword: ""
  azureMonitorWorkspaceId: ""
  applicationinsightsConnectionString: ""
  jwtIssuerUri: ""

nodeSelector: {}

tolerations: []

affinity: {}

