apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimentation-service
  labels:
    app: experimentation-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: experimentation-service
  template:
    metadata:
      labels:
        app: experimentation-service
    spec:
      containers:
      - name: experimentation-service
        image: experimentation-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: AZURE_COSMOS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: experimentation-secrets
              key: cosmos-endpoint
        - name: AZURE_COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: experimentation-secrets
              key: cosmos-key
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: experimentation-config
              key: redis-host
        - name: OAUTH2_ISSUER_URI
          valueFrom:
            secretKeyRef:
              name: experimentation-secrets
              key: oauth2-issuer-uri
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

