apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ads-decision-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ads-decision-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ads-decision-service.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dspring.profiles.active=prod"


