apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-query-service.fullname" . }}
  labels:
    {{- include "search-query-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "search-query-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "search-query-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "search-query-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AZURE_COSMOS_ENDPOINT
              value: {{ .Values.azure.cosmos.endpoint }}
            - name: AZURE_COSMOS_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: cosmos-key
            - name: AZURE_SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: servicebus-connection-string
            - name: AZURE_SEARCH_ENDPOINT
              value: {{ .Values.azure.search.endpoint }}
            - name: AZURE_SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: search-api-key
            - name: AZURE_SEARCH_INDEX_NAME
              value: {{ .Values.azure.search.indexName }}
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
