apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recommendations-service-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: recommendations-service

