spring:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    azure:
      cosmos:
        endpoint: http://localhost:8081
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DFE=
        database: moderation

azure:
  content-safety:
    endpoint: http://localhost:8089
    key: dummy

logging:
  level:
    root: INFO


