spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edgecdncontrol
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    azure:
      appconfiguration:
        enabled: false
      keyvault:
        secret:
          enabled: false
      cosmos:
        endpoint: https://localhost:8081
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==

azure:
  subscription-id: ${AZURE_SUBSCRIPTION_ID:00000000-0000-0000-0000-000000000000}

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318

logging:
  level:
    root: INFO
    com.youtube.edgecdncontrol: DEBUG

