spring:
  application:
    name: video-upload-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:youtube_video_upload}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth/realms/youtube}

# Azure Configuration
azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
    container-name: video-uploads
  
  servicebus:
    connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING:}
    queue-name: video-upload-orchestration

# Resilience Configuration
resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        retryExceptions:
          - java.net.SocketTimeoutException
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
  
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        slowCallDurationThreshold: 5000ms
        slowCallRateThreshold: 100
        recordExceptions:
          - java.util.concurrent.TimeoutException
          - java.io.IOException

# Upload Service Configuration
upload:
  max-file-size: 268435456000  # 256 GB in bytes
  min-file-size: 1024  # 1 KB in bytes
  pre-signed-url-expiration-minutes: 60
  chunk-size-mb: 100  # 100 MB chunks for resumable uploads
  quota:
    default-daily-limit-gb: 100  # 100 GB per day
    default-weekly-limit-gb: 500  # 500 GB per week
    default-upload-limit: 20  # Max 20 uploads per day

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    root: INFO
    com.youtube.videouploadservice: DEBUG
    org.springframework.security: DEBUG
    com.azure: INFO

