apiVersion: v1
kind: ServiceAccount
metadata:
  name: feeds-service
  namespace: youtube-mvp
  annotations:
    azure.workload.identity/client-id: "${WORKLOAD_IDENTITY_CLIENT_ID}"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: feeds-service-identity
  namespace: youtube-mvp
spec:
  type: 0
  resourceID: "/subscriptions/${SUBSCRIPTION_ID}/resourcegroups/${RG_NAME}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/feeds-service-identity"
  clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: feeds-service-identity-binding
  namespace: youtube-mvp
spec:
  azureIdentity: feeds-service-identity
  selector: feeds-service

