apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "content-id-service.fullname" . }}
  labels:
    {{- include "content-id-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "content-id-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "content-id-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.spring.profiles.active | quote }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: database-url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: database-password
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: AZURE_COSMOS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: cosmos-endpoint
        - name: AZURE_COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: cosmos-key
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: storage-connection-string
        - name: AZURE_SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ include "content-id-service.fullname" . }}-secrets
              key: servicebus-connection-string
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

