apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "notification-service.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notification-service.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector: {}


