apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "notification-service.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notification-service.name" . }}


