apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "notification-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080


