apiVersion: v1
kind: Namespace
metadata:
  name: monetization

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monetization-service
  namespace: monetization
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monetization-service
  template:
    metadata:
      labels:
        app: monetization-service
        version: v1
    spec:
      containers:
      - name: app
        image: monetization-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: url
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: AZURE_SB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: sb-connection-string
        - name: PAYMENT_WEBHOOK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: webhook-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: monetization-service
  namespace: monetization
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: monetization-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: monetization-service-hpa
  namespace: monetization
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monetization-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: monetization-service-pdb
  namespace: monetization
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: monetization-service

