spring:
  application:
    name: observability-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:azure}
  
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/observability}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  cloud:
    azure:
      appconfiguration:
        enabled: ${APP_CONFIG_ENABLED:true}
        endpoint: ${APP_CONFIG_ENDPOINT:}
        stores:
          - endpoint: ${APP_CONFIG_ENDPOINT}
      
      keyvault:
        secret:
          enabled: ${KEY_VAULT_ENABLED:true}
          endpoint: ${KEY_VAULT_ENDPOINT:}
          properties:
            - secret-name: datasource-password
            - secret-name: redis-password
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      azure-monitor:
        enabled: ${AZURE_MONITOR_ENABLED:true}
        connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:}
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.youtube.observabilityservice: DEBUG
    io.opentelemetry: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

resilience4j:
  retry:
    instances:
      azureMonitorQuery:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - com.azure.core.exception.AzureException
  circuitbreaker:
    instances:
      azureMonitorQuery:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
  ratelimiter:
    instances:
      syntheticCheck:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 5s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

info:
  app:
    name: Observability & SRE Tools Service
    description: SLO exporter, synthetic checks, alert configuration
    version: 1.0.0

# Azure Monitor configuration
azure:
  monitor:
    workspace-id: ${AZURE_MONITOR_WORKSPACE_ID:}

# SLO configuration
slo:
  recalculation:
    interval-ms: 300000  # 5 minutes

# Synthetic check configuration
synthetic:
  check:
    interval-ms: 60000  # 1 minute

