spring:
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/observability
    username: postgres
    password: postgres
  
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ssl:
        enabled: false
  
  cloud:
    azure:
      appconfiguration:
        enabled: false
      keyvault:
        secret:
          enabled: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/.well-known/jwks.json

logging:
  level:
    root: INFO
    com.youtube.observabilityservice: DEBUG
    org.springframework.web: DEBUG

azure:
  monitor:
    workspace-id: local-workspace-id

# Disable schedulers in local mode for manual testing
slo:
  recalculation:
    interval-ms: 0  # Disabled

synthetic:
  check:
    interval-ms: 0  # Disabled

